### PR TITLE
Switch testall.g to use TestDirectory

### PR DESCRIPTION
**Pull request by fingolfin**
This has the advantage that the tests produce an exit code indicating the
status of the tests, and also uniform defined output, both of which we can be
checked in an automated fashion for the GAP distribution.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Without this PR, even although the tests are passing, we are unable to detect this automatically - see e.g. test logs at https://travis-ci.org/gap-system/gap-docker-pkg-tests/jobs/278119200

**Comment by fingolfin** [comment]
@chsievers Any chance you might merge this and make a new release in the coming weeks? then we could include it with GAP 4.9 (perhaps 4.9.1)

**Comment by olexandr-konovalov** [comment]
@chsievers also, if you would like any help with using ReleaseTools and GitHubPagesForGAP to host it under gap-packages.github.io or under your GitHub account, please let us know.

**Comment by chsievers** [comment]
Done in commit a1c994c.

**Pull request closed without merging**
