### PR TITLE
PackageInfo.g: add License field

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@chsievers would you please consider merging this PR, and then making a release of the package? Thank you

**Comment by chsievers** [comment]
@fingolfin What's the reason for wanting a new release with only this formal change?
When I saw the patch, I judged it as nice-to-have, whenever a new version might come...
I'm also confused why one would want to remove comments about the format.

**Comment by fingolfin** [comment]
The reason for wanting a new release is that otherwise, this change may never reach the GAP package distribution, or may only reach it in many years. But we would like to make use of the licensing information as soon as possible, and so do upstream packages (e.g. for Linux distributions such as Debian).

As to the removed comments inside `PackageDoc`: the `Archive` field was deprecated many years, and the comment was referring to that. It makes no sense these days and is actively misleading.

**Comment by fingolfin** [comment]
@chsievers so, any reason for not merging this?

**Comment by fingolfin** [comment]
@chsievers ping?

**Comment by fingolfin** [comment]
The fact that this hasn't been processed after 4 months kind of underlines my point, I think ;-)

**Comment by fingolfin** [comment]
@chsievers ping?

**Comment by fingolfin** [comment]
@chsievers ping again?

I've also tried to email you. It looks as if this package is abandoned and we need to fork it.

**Comment by fingolfin** [comment]
Dear @chsievers, unfortunately it seems you are busy with other things, which is perfectly understandable. Since we haven't gotten a reply from you to inquiries in the past couple years, we have now decided to fork FGA for the time being and ship our fork with GAP. Should you ever regain interest and time in maintaining FGA, I'd be happy to work with you on re-integrating the forks.

**Pull request closed without merging**
